micronaut:
  application:
    name: Store
  server:
    port: 3000
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/sales
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'sa'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
        show_sql: false
flyway:
  datasources:
    default:
      locations: classpath:db/migration
